services:
  postgres:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: gbbgabriel
      POSTGRES_PASSWORD: gbbgbbgbb
      POSTGRES_DB: venda-dev-food
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
